### ISSUE TITLE
[feature requests]  1) merge duplicate folders. 2) find duplicates by URL.

### ISSUE THREAD

**Issue by nerdCopter** [vaeth/bookmarkdupes#103]
* feature request: merge duplicate folders (case insensitive)
* feature request: find duplicate URL's (Seemingly bookmarkdupes only finds duplicate title's, unless i'm mistaken)

reference: https://addons.mozilla.org/en-US/firefox/addon/bookmarks-clean-up/

**Comment by vaeth** [comment]
1. Won't happen: Bookmarkdupes is specialized for deleting bookmarks only, not for re-organizing
2. bookmarkdupes detects duplicates *only* by URL. Only in expert modes, you can do some tricks like replacing the URL with its name for the comparison.
