### ISSUE TITLE
Match trailing slash?

### ISSUE THREAD

**Issue by ipkpjersi** [vaeth/bookmarkdupes#107]
This isn't really a bug, more of a question. How do I match a tailing slash (a slash on the end of a URL) so it can detect `https://google.com` and `https://google.com/` as dupes?

Right now, my rules look like this:
![](https://i.imgur.com/XCTS2DJ.png)

**Comment by vaeth** [comment]
Create a modify rule: Replace URL matches `/$` by `` (leave empty).

**Comment by ipkpjersi** [comment]
I tried this, and it did not work, it is still showing only exact matches like `https://google.com` matching `https://google.com`, it does not yet match `https://google.com` with `https://google.com/`:

![](https://i.imgur.com/q0hqf0P.png)

Did I make a mistake?

**Comment by vaeth** [comment]
Here, it had worked: I created  a copy of the bookmark https://mail.google.com/mail/ without the trailing slash, disabled all other rules and pressed "Dupes", and the bookmark was found among the duplicates. Maybe something in combination with your other rules break, or maybe your bookmarks differ by something else?
BTW, I realize that rule 6 should already cover (one or more) trailing /, anyway.

**Comment by vaeth** [comment]
Just a random idea why it might have failed for you: You have to leave "Expert mode" checked (that is, opened), if you want to use the rule. "Expert mode" is not a "configuration" setting but really active only when it is opened.

**Comment by ipkpjersi** [comment]
Yep you were right, I did not leave Expert mode enabled, and rule 6 did cover the trailing / so it now works perfectly (and even finds bookmarks with https:// vs no protocol as dupes).

Thanks!
