### ISSUE TITLE
is it broken after some firefox update?

### ISSUE THREAD

**Issue by Lamer87** [vaeth/bookmarkdupes#108]
Hi, I've been using this extension for a long time, in the last few days I don't know why but by clicking on "Dupes" a series of NOT duplicate links appear, but it seems that they are considered in non-existent subfolders, with the same name as a parent folder.

example:

1- Sites | gaming sites | xxx sites | link to page
2- Sites | gaming sites | xxx sites | xxx sites | link to page
3- Sites | gaming sites | xxx sites | xxx sites | xxx sites | link to page
11- ... for exactly 11 lines of dupes for each link I have in bookmarks subfolders.

So the folder "xxx sites" exists only once, there are no other real subfolders with the same name.

Tried reinstalling the extension.
Never touched "expert mode".

If I click on "select a folder to get corresponding...", folders are all correct, no doubled subfolders.

**Comment by Lamer87** [comment]
Ok I solved it.
Saved all bookmarks from firefox, deleted it all in firefox, restored from the file, now it works.
Sorry.

**Comment by vaeth** [comment]
So I guess that it is not reproducible anymore. Closing.
