### ISSUE TITLE
Add http/https deuplicates

### ISSUE THREAD

**Issue by BUZZARDGTA** [vaeth/bookmarkdupes#109]
Hello, may you please consider adding an option that allows us to detect those both as a duplicate:
http://www.google.com/
https://www.google.com/

**Comment by vaeth** [comment]
1. Open "Expert mode"
2. Make sure that example rule 7 (the one containing http and https)  has the radio button "Modify", all other rules are "Off" (you probably only need to change the latter.)
3. You must keep "Expert mode" open while searching for dupes.

**Comment by BUZZARDGTA** [comment]
That's super sick dude, you legend, good work there; Thanks you for your work on the extension. It is daily very useful to me and just: THANKS 💜 !
