### ISSUE TITLE
add button to 'delete all dupes in same folder'

### ISSUE THREAD

**Issue by AlanJayWeiner** [vaeth/bookmarkdupes#29]
As mentioned in another issue, I've got a *lot* of bookmarks with a ton of duplicates.

I would like a button to delete all the duplicates in the same folder.

(I have so many bookmarks and duplicates, the only messages I've seen are 'Searching' and 'Searching 80255) exact dupes in 21412 groups' - which gives an idea of how many bookmarks and dupes I have.

I've folded a lot of the duplicate folders together (e.g., instead of 5 folders of 'python' I now have one, with 5 of each entry).

I did manually delete exact duplicate folders, but many folders are "all bookmarks at (some date)" - so include some of yesterday's bookmarks with some added and/or deleted.  Which means many duplicates...

Being able to delete all the duplicates in the same folder would be awesome - that would take care of the majority of my duplicates.

**Comment by vaeth** [comment]
> (80255) exact dupes in 21412 group

So the numbers you have are not much larger than the numbers I used for testing.
When you see this message, the calculation has already finished; firefox should just need some time to actually display the results in the window. If that takes forever (and it is not a lack of memory issue), something else is wrong.

> Being able to delete all the duplicates in the same folder would be awesome

Since there might be a huge number of folders, I did not find a reasonable way to express this in a GUI. However, bookmarkdupes-3.0 will support selecting categories (which are the top-level folders, usually "Bookmark Menu" and "Bookmark Toolbar"):
You might temporarily move all your bookmarks to the "Bookmark Toolbar" and the "duplicate folders" to "Bookmark Menu" and then press the button "In groups with “Bookmark Toolbar” mark all but these".

**Comment by vaeth** [comment]
bookmarkdupes-3.0 is now released

**Comment by vaeth** [comment]
bookmarkdupes-4.0 (currently only in github master branch) has a more luxury folder selection.

**Comment by AlanJayWeiner** [comment]
Hey Martin!
Was typing up a message - then saw you're on 4.0...    :)

Before that, thank you for working on this add-on!   I may be having
problems just because I'm an extreme case; if that's true, no worries - get
it to be good for 90% of cases and ignore my stupid number of duplicates.
:)

Haven't installed 4.0 yet - before that, some notes...

For deleting only duplicates that are in the same folder...
maybe "delete exact dupes in same exact folder" ?   or "delete exact dupes
within each folder" ?

Rather wordy, but it seems clear to me what it will do.  Does it hit you
the same way?   (other folks - same question; if 20 people say "that's
perfectly clear" then it's a reasonable wording...)

I like the tips when hovering over a button.

I saw the extra buttons, but even with the tips I wasn't sure exactly what
will happen.


After I posted that I hadn't ever seen the list, I *did* start seeing the
list.  :)    I just had to wait long enough for it to appear.
Subjectively it takes a long time, but I didn't time it with a stopwatch.

Selecting a bookmark (or several) does take a (subjectively) long time.
3-4 seconds or longer each.   selecting several takes much longer.   It
feels like it'd just be easier to walk through the bookmarks manually.
(hence, back to the "delete exact dupes in exact same folder" request)

With your test database - how many duplicates are there?

The message I get is:
    74044 (of (80164) exact dupes in 21370 groups

Does that mean I've got a total of 80164 bookmarks, and of those there are
74044 duplicates, so I have (80164-74044 =) 6120 unique URLs?   (wow!  I
didn't realize there were that many duplicates of that few URLs!)


These are timings with 3.0...

click on double-star icon  (timings with stopwatch)
immediately see small message 'bubble' below icon
0:23 expands to larger message bubble with scroll bars; no buttons or text
2:23 (!) buttons and bookmarks appear

clicked 'Display URL'
then clicked elsewhere so message disappeared
click on double-star icon  (again, timings with stopwatch)
immediately see small message 'bubble' below icon
0:37 expands to larger message bubble with scroll bars; no buttons or text
6:31 (!!!) buttons and bookmarks appear

2:23 and certainly 6:31 are insanely long - then I realized the buttons
didn't appear until I moved the mouse.
Verified this - waited 20+ minutes after the larger message appeared
(without buttons/text yet)
(didn't really wait - went off made coffee and food...  :)
touched the mouse and the buttons and URLs appeared instantly.

I've deleted some bookmarks since I took those timings, but only a few
hundred.

New timings (again, with stopwatch):
larger dialog appeared at about 0:29
moved mouse around - the buttons and text appeared 3 or 4 seconds later.

That was with 'display URL' checked.

an anomaly - repeating that, the larger dialog didn't appear; I waited 45
seconds and started again.

un-checked 'display URL'
larger dialog at 0:08, buttons and bookmarks at 0:16

repeating, 0:11 and 0:24
then 0:22 and 0:31

I'm tempted to erase the timings from earlier, but it's useful to note that
moving the mouse helps, and maybe someone else has reported long times...

I think seeing the initial small dialog appear, without any visible
activity was throwing me before, when I thought the list wasn't ever
displayed.   (see how cleverly I made it your fault?!!  :)



A couple of other things - my bookmarks are pretty long - things like:
bookmarks/imported from chrome/imported by chrome from firefox/another
import from somwhere else/on the date of somewhen/sorted by
topic/software/python/something else...

The message with the URLs doesn't use the full width of the screen, so I'm
scrolling left-and-right a lot.  Can it use more of the screen width?


I found I didn't like seeing the URL to the right of the bookmark - it made
it harder to see; the bookmark name/location and the URL blurred together
(ok, so I need newer glasses...)
My preference would be to see:
    https://amazon.com
    bookmarks/foo/bar/shopping
    bookmarks/stores
    bookmarks/stores
    bookmarks/fun-fun-fun

in this case, showing two of the duplicates in the same folder.


Btw, I did like seeing the numbered order of the bookmarks, indicating
their date.  Didn't help me too much; sometimes I'd moved things into
topics, but wasn't necessarily the oldest or the newest...  But I'd expect
it to be useful typically.

I just noticed this is so long - I'll leave it for now and see how 4.0
works.

All the best,
Alan

**Comment by vaeth** [comment]
> maybe "delete exact dupes in same exact folder" ?   or "delete exact dupes within each folder" ?

I think this should be solved by 4.0.

> Can it use more of the screen width

Firefox has its own algorithm for selecting the width of popups. I am not sure whether it can be overridden by .css, but even if it is possible I prefer to avoid using css since it will easily break for some users (e.g. with a small screen).

**Comment by vaeth** [comment]
Now Urls (and or text after ?) are displayed in a separate paragraph.

Since now tabs are used, the issue with the screen width should be solved, too.

**Comment by AlanJayWeiner** [comment]
I like the tab a lot!   Much easier and faster!

I'll write more in the other message (where you wrote it's almost a
complete rewrite - I did some (minimal) testing and timing.)

Al

**Comment by vaeth** [comment]
Since bookmarkdupes-4.0 is now released, I am closing this bug.
Feel free to open another one if you think that the issue has not been solved satisfactory.
