### ISSUE TITLE
FF 55 bug

### ISSUE THREAD

**Issue by perdolka** [vaeth/bookmarkdupes#38]
Looks like the "star" button doesn't work in Firefox 55.0.3 (x64).
When I click on it - nothing happens.
Also, I tried to launch a browser with disabled addons (except Bookmark Dupes).

**Comment by vaeth** [comment]
On FF57 (linux) it works, but the tab has a different background colour (grey) than when testing (where it was white).
It seems like loading an officially signed .xpi works differently than loading for debugging.

I don't know how to fix this.

(I can hardly make official releases only for testing...)

**Comment by vaeth** [comment]
Maybe it helps if you start with a clean profile?

I had already realized since quite a while that I have to remove addonStartup.json.lz4 to get proper updates of system-wide installed extensions.

**Comment by vaeth** [comment]
The background colour seems to be related with some profile settings which I had.

Still no idea why it does not work for you with FF 55; all features of the tab API which I use are listed to work with FF 45.

**Comment by vaeth** [comment]
By accident, I had now access to a Windows laptop w/ FF 57. It also works there with a sane background colour (almost white). It really seems to be related with FF 55 (or possibly with the profile).

**Comment by perdolka** [comment]
I tried with a new clean profile and its didn't help.
Just now, I updated FF to 56.0.2 (x64) - addon works very well.

**Comment by perdolka** [comment]
I tried with a new clean profile and its didn't help.
Just now, I updated FF to 56.0.2 (x64) - addon works very well.
upd
Also, works fine on 52.5.2 ESR (64) but still doesn't work on 55.0 - 55.0.3
upd
The only solution I found for 55 is to use the tab address (moz-extension://xxxxx/data/tab/index.html) as pinned tab or bookmark.

**Comment by vaeth** [comment]
I still have no idea why it does not work. I checked again all functions used in background.js, but they are all documented to work since 45.0.

If one could rely that the xxxxx is fixed for all versions of the extensions, perhaps I should document the workaround. I have no idea what the xxxxx refers to: I had explicitly named the ID of the extension in the manifest.json to avoid getting assigned such a "random" number, but using that ID instead of xxxxx does not work.

**Comment by perdolka** [comment]
> but using that ID instead of xxxxx does not work.

It seems that all WE-addons show generated ID instead "name" in their tabs address.
Don't know why.

**Comment by vaeth** [comment]
The workaround is now documented in the README.md and on the mozilla page for the addon.

**Comment by perdolka** [comment]
Sad, but now I realized that this random ID is generated **individually**, so the workaround will not help the most users, i guess so.
https://www.ghacks.net/2017/08/30/firefox-webextensions-may-identify-you-on-the-internet/

P.S.
I don't think there's a lot of 55+Bookmark Dupes-users . 
So, maybe you don't have to worry about that?
It would be easier to mark this version as incompatible on 55s.
**But** I'm not sure that its not my strange local problem.

**Comment by vaeth** [comment]
I was suspecting this ID issue.
Now that I know that this can identify my machine, I would like to get rid of the information.
Therefore, I rebased the repository again. Unfortunately, currently this information is still visible in your PR; maybe you can rebase yours, too? For this reason, I neither comment nor merge your PR in the moment. I will add the corresponding data manually (probably the title should be internationalized anyway).

**Comment by vaeth** [comment]
I forgot: I do not think that it is possible to mark an extension incompatible with a particular FF version; I could claim that it is only FF 57+ compatible, but this would probably exclude FF 52 users which is presumably a bad idea.

**Comment by perdolka** [comment]
To be honest, I don't know how to delete (or rebase) this PR.
I made the changes directly on github, then removed the fork.
I didn't make changes in the README.md and don't know how this commit got into my PR.
Maybe you have rights to remove my PR or commit ?

**Comment by vaeth** [comment]
>  don't know how to delete (or rebase) this PR.

I don't think it is possible: The PR was based on a commit which no longer exists. I guess that in order to keep the PR, github has to keep a reference on that commit somehow.
I do not know any way to delete a PR with github.

**Comment by perdolka** [comment]
I'm sorry about that.
I will try to contact the support, maybe they can remove.

**Comment by perdolka** [comment]
**Hurray, support deleted this PR at my request.**

Also, seems that I found a way to change ID. 
I tested these steps on 56.0.2 (x64) several times and it works.

0 run FF
1 uninstall Bookmark Dupes
2 **close FF**
3 run FF
4 install Bookmark Dupes again

After these steps the ID will be re-generated.

**Comment by vaeth** [comment]
> Hurray, support deleted this PR at my request.

Thanks a lot!

> Also, seems that I found a way to change ID.

OK. So it is clear that this is not an easy workaround for the problem, because the users have no easy way to find out the ID unless they run a working firefox installation in parallel.

SInce it seems to be a problem with FF 55 only (and probably FF 55 should not be used for a long time for security reasons anyway), I think I will just leave the issue open and keep it documented as "known bugs".

**Comment by perdolka** [comment]
~~I think I found~~ where is stored ID.
~~Profile folder > extensions.json
Just open with notepad++ and search for "Dupes" (for example).
Somewhere nearby will be ID.~~
about:debugging

upd
The ID is generated (is written to the extensions.json) BEFORE the opening of the tab.
So this is a working workaround.

**Comment by vaeth** [comment]
A few minutes before your posting, I had released 4.2:
This contains an options page which should have a link to the address.
If this (hopefully) works, this would probably be the most convenient way for the affected users.

**Comment by perdolka** [comment]
Yes, it works.
Checked on 55.0.3 (x64)

**Comment by vaeth** [comment]
> Yes, it works.

Great! Thanks for the testing!
