### ISSUE TITLE
Cannot install this addon in Firefox Offical Website

### ISSUE THREAD

**Issue by xtay573269555** [vaeth/bookmarkdupes#44]
Hi,
    I tried to install Bookmark Dupes v4.2 or v4.1 at https://addons.mozilla.org/zh-CN/firefox/addon/bookmark-dupes/ , but it failed and return the following error message: "The add-on downloaded from this site could not be installed because it appears to be corrupt."
    I downloaded the xpi file "bookmark_dupes-4.2-fx.xpi", and the filesize is 39014 bytes, the md5sum is 0972e813bdf4c88c4a99ce1530badfa4. Is something error with Mozilla or the add-on ?

**Comment by vaeth** [comment]
filesize and md5sum are correct.
I don't know why installing from the official site failed. Signing has been done by mozilla, so there shouldn't be a certficate issue. But perhaps there are special rules for China?
Or a first download had a transfer error?
Or perhaps you use some other addon or too restrictive .config setting?
Can you install the xpi from disk (with file:///)?

**Comment by xtay573269555** [comment]
The following is my steps.

1. I created a new Firefox profile to install the add-on, but failed.
2. I tried to install the add-on from https://addons.mozilla.org/en-US/firefox/addon/bookmark-dupes/ , and failed too.
3. I tried to download the xpi file from https://addons.mozilla.org/en-US/firefox/addon/bookmark-dupes/ , and install the xpi from local disk, it doesn't work.
4. I open a vpn (American IP) and set all internet connection force using the VPN, and then repeat the step 2, and it failed too.

My Firefox version is 45.9.0 ESR. I attach the Firefox information as 'Firefox_information.txt' exported from URL about:support .
Can you try to reinstall the add-on from https://addons.mozilla.org/en-US/firefox/addon/bookmark-dupes/ ?

[Firefox_information.txt](https://github.com/vaeth/bookmarkdupes/files/1603647/Firefox_information.txt)

Here are some screenshots.
![2018-01-04_222854](https://user-images.githubusercontent.com/5844466/34568858-01ebd30a-f15f-11e7-896f-8d6b73e0ff20.png)
![2018-01-04_223349](https://user-images.githubusercontent.com/5844466/34568892-224490a6-f15f-11e7-9b60-e0db228c7fee.png)
![2018-01-04_223741](https://user-images.githubusercontent.com/5844466/34568910-2cede908-f15f-11e7-81a8-512e13ef207a.png)
![2018-01-04_224331](https://user-images.githubusercontent.com/5844466/34568936-36003d7a-f15f-11e7-89d6-4d3596c31396.png)
![2018-01-04_224351](https://user-images.githubusercontent.com/5844466/34568942-3b1e5828-f15f-11e7-8e5e-a5c5054236a6.png)
![2018-01-04_224356](https://user-images.githubusercontent.com/5844466/34568963-470f731a-f15f-11e7-8552-d8312106cb07.png)
![2018-01-04_224403](https://user-images.githubusercontent.com/5844466/34568973-4c5f7568-f15f-11e7-82db-77f23eb8055d.png)

**Comment by vaeth** [comment]
Apparently, FF 45 does not even support basic keys like the extension name in manifest.json:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/name

I suppose that this (or another key in manifest.json) is the reason for the failure.

So I am afraid that the minimal firefox version required by the extension must be increased to at least 48. I modified the information correspondingly (in the moment only for release 4.2, but probably soon for all releases):

The only solution I see is that you have to upgrade your firefox.

**Comment by xtay573269555** [comment]
OK, thanks.
