### ISSUE TITLE
Radio buttons may be broken - blocking of columns works weird.

### ISSUE THREAD

**Issue by perdolka** [vaeth/bookmarkdupes#56]
<a href="http://piccy.info/view3/11999920/ec8ca3d0c937038e6eb51d58948f5e6a/" target="_blank"><img src="http://i.piccy.info/i9/d80d403de40c6669bbe883152298ed84/1516961005/36914/1207467/2018_01_26_11_51_44_min_500.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-01-26-10-03/i9-11999920/374x446-r" target="_blank"><img src="http://i.piccy.info/a3/2018-01-26-10-03/i9-11999920/374x446-r/i.gif" alt="" border="0" /></a>

**Comment by vaeth** [comment]
Thanks for reporting.
This is a regression due to adding "space" columns: In 5.1, I had forgotten to adapt the column numbers in the function which is called for radio button changes.

5.2 with the fix is already released
