### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by perdolka** [vaeth/bookmarkdupes#66]
FF 60.0b4 (x64)
bookmarkdupes v5.6

The buttons become inactive after clicking on them.
Also, the addon doesn't find my bookmarks.
<a href="http://piccy.info/view3/12168329/5ddeac5503d6fba490a4f95577758a16/" target="_blank"><img src="http://i.piccy.info/i9/6c922b7c3cbc2fef4a42a632ff95a2fc/1521469841/9106/1225975/sshot_1_500.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-03-19-14-30/i9-12168329/500x118-r" target="_blank"><img src="http://i.piccy.info/a3/2018-03-19-14-30/i9-12168329/500x118-r/i.gif" alt="" border="0" /></a>

**Comment by vaeth** [comment]
Thanks a lot.
As usual: a hasty change before the release had unexpected side effects ;(
Fixed version is already in master branch and will be released ASAP
