### ISSUE TITLE
Incorrect duplicate recognition

### ISSUE THREAD

**Issue by git70** [vaeth/bookmarkdupes#80]
Hello
I am not a professional and I can not use Expert Mode.
The problem is:

Three different URLs:
1. https://gist.github.com/kennwhite/1f3bc4d889b02b35d8aa#gistcomment-1854294
2. https://gist.github.com/kennwhite/1f3bc4d889b02b35d8aa#gistcomment-1930733
3. https://gist.github.com/kennwhite/1f3bc4d889b02b35d8aa#gistcomment-1931470

they are recognized as one:
https://gist.github.com/kennwhite/1f3bc4d889b02b35d8aa

Please help me how to fix it.

**Comment by vaeth** [comment]
I cannot reproduce it: If I don't enable expert mode, the above three bookmarks are not considered as dupes. Maybe you had enabled expert mode when you pressed the "dupes" button?

(However, even with the default rules in expert mode the bookmarks are not considered duplicate, here.)

Of course, in expert mode it is simple to write rules which consider these bookmarks as dupes. For instance, if you build a "modify" rule with the only field "replace URL matches"  \#.* (which will cut the symbol # and everything after it).

**Comment by git70** [comment]
These are some magic!
Today I checked again and everything is ok.
I do not know what I broke down and fixed.
Thank you for your answer and I apologize for the confusion!
