### ISSUE TITLE
Possible to reload favicons during check?

### ISSUE THREAD

**Issue by ReporterX** [vaeth/bookmarkdupes#81]
Is it possible to reload favicons of all bookmark itmes during check? Thank you.

**Comment by vaeth** [comment]
I don't know whether it might be possible for a WebExtension at all to load favicons.
In any case, bookmarkdupes does not access the web, and this is a functionality which is also not planned for future version.

**Comment by ReporterX** [comment]
I see. Thank you for your reply. 
It is possible since I see some bookmark addons do it. It seems it could be done in several ways: by the hard way (i.e. loading the tab to get the favicon), using some favicon sites like api.faviconkit.com to get favicons.

**Comment by vaeth** [comment]
I have no doubts that some bookmark addons do it. Many of these are probably specialized on testing validity of bookmarks, and then it is natural to do so.

bookmarkdupes has a rather specialized scope, and I decided rather in the beginning to include no features which require web access.

Closing as WONTFIX.
