### ISSUE TITLE
About duplicate bookmarks. 

### ISSUE THREAD

**Issue by minshifu** [vaeth/bookmarkdupes#82]
Thank you for your hard work. But sometimes it'd be useful to have duplicates. So could you pls add a function to allow that? By that I mean allowing adding the same url in different folders at the same time. Now it is impossible. Best wishes!

**Comment by vaeth** [comment]
I am not sure what you mean:

You can just un-mark the bookmarks you want to have in duplicate before you press the “Remove marked bookmarks” button.

If you even do not want to have them displayed, you can select expert mode and create a “Filter” rule (remove all other rules or switch them to "Off") for each URL you want to have in duplicate without being displayed and enter in "URL matches" a regular expression which matches that rule (e.g. escape all non-alphanumeric characters with the \ symbol).

**Comment by minshifu** [comment]
Hi, I mean duplicate urls can be bookmarked in the first place. Say there are a url A and folders B and C.  I want the url A to be added into folder B and folder C at the same time. Now that is impossible. Could you help achieve that? Thank you and best regards!

**Comment by vaeth** [comment]
Despite its name, the purpose of the extension is to _eliminite_ duplicate bookmarks, not to generate some. Although  the latter might be possible, this is outside of the aim of the extension.

**Comment by minshifu** [comment]
Sorry，I have been very preoccupied recently. Thank you for your explanation.
