### ISSUE TITLE
extension not signed in Firefox 43+

### ISSUE THREAD

**Issue by demoklion** [vaeth/bookmarkdupes#83]
> Starting with Firefox 43, add-on extensions and multi-item add-ons that include extensions need to be signed by Mozilla before they can install in release and beta versions of Firefox. 

[More info on mozilla's site](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution#Signing_your_add-ons)

**Comment by polyzen** [comment]
Seems like you might have ran into this:
https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by vaeth** [comment]
Thanks for pointing out the firefox bug.

That being said: The extension which can be downloaded from the mozilla site is also signed by mozilla.

**Comment by demoklion** [comment]
bug in firefox, not in this extension. sorry!
