### ISSUE TITLE
Highly Recommended Suggestion!! "Non-Duplicates"

### ISSUE THREAD

**Issue by questionabout** [vaeth/bookmarkdupes#87]
I learnt of this plugin a month or so ago. It is very useful and much appreciated.

It would be even more useful if there were the option to print out the "Non-Duplicates". This way, I can see the *difference* between an old and a new bookmark set, and manually decide for each bookmark "Have I deleted it from the local bookmarks deliberately" -> I delete the singlet; or "Have I added it to the imported bookmarks (from another operating system)?" -> I keep the singlet.

From there I can go back to printing the Dupes and delete them.

It would save a lot of time in correcting my Bookmarks.

Thank you

**Comment by vaeth** [comment]
I can see how it would be useful. However, implementation would have to be very careful to not break the "standard" workflow. There would need to be an additional button or switch.
In the moment, I certainly do not have enough time to think about such an implementation.

**Comment by vaeth** [comment]
Fixed in master branch (and merged to nostrip branch).
I am waiting a few days for translations and then release.
