### ISSUE TITLE
"Move marked bookmarks to "Dupes"" broken

### ISSUE THREAD

**Issue by TheFrenchGhosty** [vaeth/bookmarkdupes#93]
Since the 6.1 update, "Move marked bookmarks to dupe" doesn't work, when started it will just hang and not do anything, everything else is working.

The problem is here for the bookmarks and the folders.

6.0 is working perfectly.

Browser: Icecat (Firefox 60.7.0esr) (since it wasn't reported before I'm guessing that it's not happening in later version of Firefox)

Gif of the issue:

![dupes](https://user-images.githubusercontent.com/47571719/76012375-14b7eb80-5f0e-11ea-9206-9ec2e069660f.gif)

**Comment by vaeth** [comment]
Thanks for the report. This should be fixed in v6.3.

**Comment by TheFrenchGhosty** [comment]
Working, thanks for the quick fix!
