### ISSUE TITLE
How to find duplicate only if URL and TITLE both match?

### ISSUE THREAD

**Issue by endolith** [vaeth/bookmarkdupes#94]
I don't understand if this is possible.  It seems like the rule would be 

> “Replace URL matches” `.+` “by” `$URL$TITLE`

But it says "this special meaning is only active if this is the full replacement text", so they can't be combined like that?  But then how would they be combined?  It says "one can combine several rules to work around that limitation if necessary" but how to combine them if they both completely replace the text?

**Comment by vaeth** [comment]
You are right: AFAICS, it is currently impossible to produce such a useful combination.

Version 6.4 will allow to use also $&$TITLE, TITLE$&, $&$URL, $URL$&, $&$NAME, $NAME$&.

**Comment by endolith** [comment]
Ok, great. About how long until that version is available?

**Comment by vaeth** [comment]
Released

**Comment by endolith** [comment]
So I replace `.+` with `$&$TITLE` and it will append the title to the URL and use the combination for matching?

**Comment by endolith** [comment]
Looks like that's working.  Thanks!!!  

Now I can clean up my 168,040 duplicate bookmarks without worrying about accidentally deleting useful information...
